//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoUongOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public int IdCTPN { get; set; }
        public int SoLuongNhap { get; set; }
        public double GiaNhap { get; set; }
        public int IdNL { get; set; }
        public int IdPN { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual Kho Kho { get; set; }
    }
}
