//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoUongOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int IdChiTietDH { get; set; }
        public int SoLuong { get; set; }
        public string GhiChuChiTiet { get; set; }
        public double GiaBan { get; set; }
        public Nullable<int> DanhGiaSanPham { get; set; }
        public int IdSP { get; set; }
        public int IdDH { get; set; }
        public string IdSizeSP { get; set; }
    
        public virtual SizeSanPham SizeSanPham { get; set; }
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
