//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoUongOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongThuc
    {
        public int DinhLuong { get; set; }
        public string DonVi { get; set; }
        public int IdSP { get; set; }
        public int IdNL { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
