//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoUongOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public int IdCTPN { get; set; }
        public int SoLuong { get; set; }
    
        public virtual ChiTietPhieuNhap ChiTietPhieuNhap { get; set; }
    }
}
